name: GP Stake News Aggregator

on:
  schedule:
    # Runs every day at 12:00 PM UTC
    # Adjust cron expression as needed using https://crontab.guru/
    # For example, '0 0 * * *' would run at midnight UTC daily.
    - cron: '0 12 * * *'
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest # Or 'macos-latest', 'windows-latest' if preferred, but ubuntu-latest is typical for scripts

    permissions: # Grant GITHUB_TOKEN necessary permissions
      contents: write # Allows the workflow to commit files back to the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use the latest Python 3 version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script
        run: python aggregator.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Update GP stake news feed"
          # Optional: Specify files/directories to commit. If omitted, all changes are committed.
          # file_pattern: "data/*.csv" 
